rules_folder: /opt/elastalert/rules/
run_every:
    minutes: 1
buffer_time:
    minutes: 15
es_host: 10.0.0.1
es_port: 9200
es_username: elastic
es_password: password
writeback_index: elastalert_status
