---
#
# Playbook to install the ELK client utilities (Debian, Cobalt Strike Specific)
#

- hosts: cs
  remote_user: "{{ ansible_system_user }}"
  vars_files:
    - group_vars/all.yml
  roles:
    - { role: elk_cs_client }
