---
#
# Playbook to install the ELK client utilities (Debian)
#

#requires Python2.7 callable as 'python' (e.g. use a symlink like 'ln -s /usr/bin/python2.7 /usr/bin/python')
- hosts: elk-deb-client
  remote_user: "{{ ansible_system_user }}"
  vars_files:
    - group_vars/all.yml
  roles:
    - { role: elk_deb_client }
